#!/bin/bash

# docker build -t alignfacehttp --force-rm .

# Check if alignfacehttp container is running
if ! docker ps --format "table {{.Names}}" | grep -q "^alignfacehttp$"; then
    echo "Error: alignfacehttp container is not running"
    echo "Please start the container with: docker run -p 15000:5000 -d --name alignfacehttp --rm alignfacehttp"
    exit 1
fi

for i in capy/*jpg dada/*jpg mama/*jpg platy/*jpg
do
    if [ ! -f aligned/$i ]; then
        curl -X POST -F file=@originals/$i -F distance=90 -F width=600 -F height=800 http://localhost:15000/align --output aligned/$i
    else
        echo skipping aligned/$i, already exists
    fi
done

for i in capy dada mama platy
do
  pushd aligned/$i
  ffmpeg -y -f image2 -framerate 12 -pattern_type glob -export_path_metadata 1 -i '*.jpg' -vf "tpad=start_mode=clone:start_duration=2:stop_mode=clone:stop_duration=2,drawtext=text='%{metadata\:lavf.image2dec.source_basename\:NA}'" ../../animated/$i.mp4
  popd
done

